"""Acceptance criterion 4 — Bates detection accuracy, by D-23's method.

    python tools/bates_acceptance.py --corpus "<MNFV root>" [--sample-pages N]
    python tools/bates_acceptance.py --negative-control "<Petrobras root>"

D-23 rules the method: a **sequence-continuity proof over the whole set**, which
catches the systematic error class a sample cannot see, plus a **hand-checked
stratified sample** for absolute correctness. It also records an assumption that
turned out not to hold, and the correction matters more than the tool:

**D-23 assumed every ground-truth number would itself be OCR of a footer stamp.**
It is not. The MNFV disclosure is a standard e-discovery production and ships its
own **load files** — ``.OPT`` (Opticon: one line per page, page-level Bates and
document breaks), ``.LFP``, ``.DAT`` (document-level Begin/End Bates) and
``.LST``. Those are the *producing party's* authoritative numbering, generated by
the production vendor at the moment the stamps were burned in, and they are not
derived from reading the stamps back. So page-level ground truth for the
2,138-document production is **authoritative, not OCR-derived**, and the accuracy
figure is a comparison against it rather than against a second reading of the
same footer.

The second half of the set — the 17 combined PDFs under ``Initial Disclosures``
and ``Supplemental`` — has **no load file**. Its ground truth is document-level
only, carried in the filenames, and D-23's caveat applies there in full.

Both are measured and both are reported separately. Collapsing them into one
percentage would be the more flattering number and the less honest one.

NOTHING HERE WRITES INSIDE THE REPOSITORY. The corpus is client material; the
report goes wherever ``--out`` points and the caller is expected to keep that
outside the working tree.
"""

from __future__ import annotations

import argparse
import csv
import io
import json
import random
import re
import sys
import time
from collections import Counter, defaultdict
from dataclasses import dataclass, field, replace
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from dociq.contracts import DocumentRecord  # noqa: E402
from dociq.identify import bates as B  # noqa: E402
from dociq.ingest import extract as ex  # noqa: E402
from dociq.ingest.pagemodel import make_page  # noqa: E402

# ---------------------------------------------------------------------------
# Ground truth 1 — the production's own load files (authoritative)
# ---------------------------------------------------------------------------

_BATES_RE = re.compile(r"^(?P<prefix>[A-Za-z][A-Za-z0-9]*?)(?P<digits>\d+)$")


@dataclass(frozen=True, slots=True)
class OptPage:
    """One ``.OPT`` line: the Bates number of one page of one image file."""

    bates: str
    image_rel: str
    doc_break: bool


def parse_opt(path: Path) -> list[OptPage]:
    """Opticon: ``Bates,Volume,ImagePath,DocBreak,,,PageCount``.

    Read positionally rather than by header — the format has no header, and a
    reader that guessed columns by name would silently produce an empty ground
    truth, which compares equal to a perfect detection.
    """
    out: list[OptPage] = []
    with path.open("r", encoding="utf-8", errors="replace", newline="") as fh:
        for row in csv.reader(fh):
            if len(row) < 4 or not row[0].strip():
                continue
            out.append(OptPage(bates=row[0].strip(),
                               image_rel=row[2].strip().replace("\\", "/"),
                               doc_break=row[3].strip().upper() == "Y"))
    return out


def split_bates(s: str) -> tuple[str, int, int] | None:
    """``(prefix, number, digit width)`` — the parts continuity is judged on."""
    m = _BATES_RE.match(s.strip())
    if not m:
        return None
    d = m.group("digits")
    return m.group("prefix"), int(d), len(d)


# ---------------------------------------------------------------------------
# Ground truth 2 — the combined PDFs, whose range lives in the filename
# ---------------------------------------------------------------------------

# Filenames use both an ASCII hyphen and an EN DASH as the range separator, and
# both must be read: a parser that knew only "-" would read the en-dash file as
# unranged and quietly drop 332 pages of the production from the continuity
# proof — an absence that looks exactly like "this file is not stamped".
_FILENAME_RANGE_RE = re.compile(
    r"^(?P<prefix>[A-Z]{2,8})\s+(?P<start>\d{3,8})\s*(?:[-‐-―])\s*"
    r"(?P<end>\d{3,8})\b")
_FILENAME_SINGLE_RE = re.compile(r"^(?P<prefix>[A-Z]{2,8})\s+(?P<start>\d{3,8})\b")


@dataclass(frozen=True, slots=True)
class NamedRange:
    path: Path
    prefix: str
    start: int
    end: int
    width: int


def parse_filename_range(p: Path) -> NamedRange | None:
    m = _FILENAME_RANGE_RE.match(p.name)
    if m:
        return NamedRange(p, m.group("prefix"), int(m.group("start")),
                          int(m.group("end")), len(m.group("start")))
    m = _FILENAME_SINGLE_RE.match(p.name)
    if m:
        return NamedRange(p, m.group("prefix"), int(m.group("start")),
                          int(m.group("start")), len(m.group("start")))
    return None


# ---------------------------------------------------------------------------
# (a) the continuity proof — the whole set, the systematic error class
# ---------------------------------------------------------------------------


@dataclass
class ContinuityReport:
    label: str
    documents: int = 0
    pages: int = 0
    findings: list[str] = field(default_factory=list)
    checks: list[str] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return not self.findings

    def render(self) -> str:
        head = (f"[{self.label}] {self.documents} document(s), {self.pages} "
                f"page(s) — {'CONTINUOUS' if self.ok else str(len(self.findings)) + ' FINDING(S)'}")
        return "\n".join([head] + [f"    check   {c}" for c in self.checks]
                         + [f"    FINDING {f}" for f in self.findings])


def continuity_from_opt(pages: list[OptPage], label: str) -> ContinuityReport:
    """Monotonic, gapless, non-overlapping, contiguous — over every page.

    Each property is checked separately and reported separately, because they
    fail for different reasons: a gap is a dropped page, an overlap is a
    document-boundary error, and a non-monotonic step is a numbering error. A
    single "continuous / not continuous" verdict would name none of them.
    """
    rep = ContinuityReport(label)
    parsed = [(p, split_bates(p.bates)) for p in pages]
    unparsed = [p.bates for p, s in parsed if s is None]
    if unparsed:
        rep.findings.append(f"{len(unparsed)} page number(s) do not parse as "
                            f"<prefix><digits>, e.g. {unparsed[:3]}")
    good = [(p, s) for p, s in parsed if s is not None]
    rep.pages = len(good)
    if not good:
        rep.findings.append("no parseable page numbers at all")
        return rep

    prefixes = Counter(s[0] for _, s in good)
    rep.checks.append(f"one prefix across the production: "
                      f"{dict(prefixes)}" if len(prefixes) > 1 else
                      f"single prefix {next(iter(prefixes))!r}")
    if len(prefixes) > 1:
        rep.findings.append(f"{len(prefixes)} distinct prefixes: {dict(prefixes)}")

    widths = Counter(s[2] for _, s in good)
    rep.checks.append(f"digit widths present: {dict(sorted(widths.items()))}")

    numbers = [s[1] for _, s in good]
    non_mono = [i for i in range(1, len(numbers)) if numbers[i] <= numbers[i - 1]]
    rep.checks.append(f"strictly increasing in file order: "
                      f"{'yes' if not non_mono else str(len(non_mono)) + ' step(s) not'}")
    if non_mono:
        rep.findings.append(
            f"{len(non_mono)} page(s) do not increase over the previous page, "
            f"first at index {non_mono[0]}")

    gaps = [(numbers[i - 1], numbers[i])
            for i in range(1, len(numbers)) if numbers[i] != numbers[i - 1] + 1]
    rep.checks.append(f"contiguous across the whole production: "
                      f"{'yes' if not gaps else str(len(gaps)) + ' break(s)'}")
    if gaps:
        rep.findings.append(
            f"{len(gaps)} break(s) in the production sequence, first "
            f"{gaps[0][0]} -> {gaps[0][1]}"
            + (f" (total {sum(b - a - 1 for a, b in gaps)} number(s) unaccounted)"))

    # Per-document: a document's own pages must be a contiguous run.
    docs: list[list[int]] = []
    for p, s in good:
        if p.doc_break or not docs:
            docs.append([])
        docs[-1].append(s[1])
    rep.documents = len(docs)
    ragged = [d for d in docs if d != list(range(d[0], d[0] + len(d)))]
    rep.checks.append(f"every document's own pages are a gapless run: "
                      f"{'yes' if not ragged else str(len(ragged)) + ' ragged'}")
    if ragged:
        rep.findings.append(f"{len(ragged)} document(s) have a gap or a "
                            f"repeat inside their own Bates range")

    spans = [(d[0], d[-1]) for d in docs]
    overlaps = [(spans[i - 1], spans[i])
                for i in range(1, len(spans)) if spans[i][0] <= spans[i - 1][1]]
    rep.checks.append(f"document ranges do not overlap: "
                      f"{'yes' if not overlaps else str(len(overlaps)) + ' overlap(s)'}")
    if overlaps:
        rep.findings.append(f"{len(overlaps)} overlapping document range(s), "
                            f"first {overlaps[0]}")
    return rep


def continuity_from_filenames(ranges: list[NamedRange],
                              page_counts: dict[Path, int],
                              label: str) -> ContinuityReport:
    """The same properties, for the set whose only ground truth is its names.

    Weaker on purpose and labelled as such: a filename range is what the
    producing party *called* the file, and the page count is what the PDF
    actually holds. Where they disagree the disagreement is the finding.
    """
    rep = ContinuityReport(label)
    rep.documents = len(ranges)
    ordered = sorted(ranges, key=lambda r: (r.prefix, r.start))
    rep.pages = sum(page_counts.get(r.path, 0) for r in ordered)

    widths = Counter(r.width for r in ordered)
    rep.checks.append(f"digit widths in the names: {dict(sorted(widths.items()))}")

    mismatched = [(r, page_counts.get(r.path), r.end - r.start + 1)
                  for r in ordered
                  if page_counts.get(r.path) is not None
                  and page_counts[r.path] != r.end - r.start + 1]
    rep.checks.append(f"named range length equals the PDF's page count: "
                      f"{'yes' if not mismatched else str(len(mismatched)) + ' mismatch(es)'}")
    for r, actual, named in mismatched:
        rep.findings.append(
            f"{r.prefix} {r.start}-{r.end} names {named} page(s) but the PDF "
            f"holds {actual}")

    for i in range(1, len(ordered)):
        a, b = ordered[i - 1], ordered[i]
        if b.start <= a.end:
            rep.findings.append(
                f"overlapping named ranges: {a.prefix} {a.start}-{a.end} and "
                f"{b.prefix} {b.start}-{b.end}")
        elif b.start != a.end + 1:
            rep.findings.append(
                f"gap in the named sequence: {a.prefix} {a.end} -> "
                f"{b.prefix} {b.start} ({b.start - a.end - 1} number(s))")
    rep.checks.append(f"named ranges tile the production without gap or overlap: "
                      f"{'yes' if not rep.findings else 'no'}")
    return rep


# ---------------------------------------------------------------------------
# (b) page-level accuracy — DocIQ's detection against the ground truth
# ---------------------------------------------------------------------------


@dataclass
class AccuracyReport:
    label: str
    pages_compared: int = 0
    correct: int = 0
    wrong: list[tuple[str, int, str, str]] = field(default_factory=list)
    missed: list[tuple[str, int, str]] = field(default_factory=list)
    false_positive: list[tuple[str, int, str]] = field(default_factory=list)
    documents: int = 0
    seconds: float = 0.0
    proposal: str = ""
    notes: list[str] = field(default_factory=list)
    matter_prefixes: list = field(default_factory=list)
    normalization_available: bool = False
    refused_reason: str = ""
    normalized: list = field(default_factory=list)
    """D-28 repairs, as ``(rel, page, what the page reads, what was written,
    rule)``. Reported in full rather than counted: a repaired locator that
    nobody can inspect is the silent correction §4 forbids."""

    by_kind: dict = field(default_factory=dict)
    """``{page kind: [compared, correct]}``.

    The headline percentage over a mixed corpus averages two different things.
    A page with a text layer and a page DocIQ had to OCR are not the same
    measurement: on the second, Bates accuracy is bounded by OCR quality, which
    D-19 characterised at mean page confidence 0.8628. Reporting one number
    hides which half a shortfall is in, and the whole point of criterion 4 is
    to know that."""

    @property
    def accuracy_pct(self) -> float:
        return 100.0 * self.correct / self.pages_compared if self.pages_compared else 0.0

    def render(self) -> str:
        lines = [
            f"[{self.label}] {self.documents} document(s), "
            f"{self.pages_compared} page(s) compared in {self.seconds:.0f} s",
            f"    proposed format : {self.proposal or '(none proposed)'}",
            f"    exactly correct : {self.correct} "
            f"({self.accuracy_pct:.3f}%)",
            f"    WRONG number    : {len(self.wrong)}",
            f"    MISSED (no stamp detected where one exists): {len(self.missed)}",
            f"    FALSE POSITIVE  : {len(self.false_positive)}",
        ]
        lines.append(
            f"    prefixes in the matter (D-28 gate): "
            f"{self.matter_prefixes or '(none)'} -> prefix repair "
            f"{'AVAILABLE' if self.normalization_available else 'REFUSED'}")
        if self.refused_reason:
            lines.append(f"    {self.refused_reason}")
        lines.append(f"    locators REPAIRED under D-28: {len(self.normalized)}")
        for row in self.normalized[:10]:
            lines.append(f"    repaired: {row}")
        for kind, (n, ok) in sorted(self.by_kind.items()):
            lines.append(f"    by page kind — {kind:9s}: {ok}/{n} "
                         f"({100.0 * ok / n if n else 0:.3f}%)")
        lines += [f"    note: {n}" for n in self.notes]
        for label, rows in (("wrong", self.wrong[:10]),
                            ("missed", self.missed[:10]),
                            ("false positive", self.false_positive[:10])):
            for row in rows:
                lines.append(f"    {label}: {row}")
        return "\n".join(lines)


FOOTER_REOCR = True
"""Whether the run exercises D-25's targeted footer re-OCR.

A module global rather than a parameter threaded through four functions,
because it is a property of the RUN and the tool runs one measurement at a
time. ``--no-footer-reocr`` sets it False, which is how the before-number is
produced with the after-code — the only honest way to attribute a delta.
"""


def has_ocr_pages(path: Path) -> bool | None:
    """Whether this PDF has any page DocIQ would have to OCR.

    Cheap: the text layer only, no recognition. It exists because the D-25 band
    pass CANNOT change a document with no such page — it is reached only when
    the OCR map is non-empty — so a re-measurement may skip those documents and
    carry their baseline result forward without weakening the figure. The
    argument is asserted in ``tests/test_footer_reocr.py``, not just stated.
    """
    try:
        from pypdf import PdfReader

        reader = PdfReader(io.BytesIO(path.read_bytes()))
        return any(len((pg.extract_text() or "").strip()) < ex._NATIVE_TEXT_FLOOR
                   for pg in reader.pages)
    except Exception:
        return None


def _document_from_pdf(path: Path, rel: str) -> DocumentRecord | None:
    """Extract one PDF through DocIQ's OWN extractor.

    Deliberately not a shortcut reader: the number being measured is the
    accuracy of what DocIQ ships, and a probe that read the footer with a
    different library would measure that library.
    """
    try:
        raw = path.read_bytes()
    except OSError:
        return None
    try:
        pages, notes = ex._extract_pdf(
            raw, ex.ExtractOptions(ocr_enabled=True, footer_reocr=FOOTER_REOCR))
    except Exception as exc:
        print(f"    ! {rel}: {type(exc).__name__}: {exc}")
        return None
    import hashlib

    return DocumentRecord(
        doc_id="", rel_path=rel, filename=path.name,
        sha256=hashlib.sha256(raw).hexdigest(), size_bytes=len(raw),
        ext=".pdf", pages=tuple(pages), notes=tuple(notes))


PROPOSAL_DOCS = 20
"""How many documents the format proposal is derived from.

TWO PASSES, AND THE REASON IS MEMORY, NOT ELEGANCE. The first version of this
function extracted every sampled document and held them all, then proposed and
compared. On the real corpus that reached **4+ GB of resident memory and the
process was killed before it printed a single accuracy figure** — three times.
A run that dies is not a bound, it is an absence of one.

So: pass 1 extracts a small prefix of the sample and proposes a format from it;
pass 2 streams the whole sample one document at a time, applies the confirmed
format, records per-page outcomes, and drops the document. Memory is bounded by
the largest single document rather than by the sample.

The cost is real and is stated rather than buried: the proposal sees
``PROPOSAL_DOCS`` documents, not the whole sample. That is also what a live run
would do if the operator confirmed early, and the number of documents the
proposal was derived from is printed with the result.
"""


def zone_only(doc: DocumentRecord) -> DocumentRecord:
    """The same document with every page reduced to its Bates ZONE.

    Stage 3 reads nothing but the zone, so this is lossless for what is being
    measured — and it is what makes ONE streaming extraction pass enough.

    D-28's third gate is a question about the MATTER ("does it carry exactly one
    proposable prefix?"), so the answer cannot be computed one document at a
    time. Holding every extracted document to answer it is what killed three
    earlier runs at 4-14 GB resident. A page's zone is at most eleven short
    lines, so the whole sample fits in a couple of megabytes.

    Lossless, not approximately lossless: re-slicing a zone gives the zone back.
    The head takes the first three of at most eleven lines, which are the
    original first three; the tail takes the last eight, which are the original
    last eight. ``tests/test_bates.py`` asserts it rather than asserting it here
    in prose.
    """
    z = B.BatesZone()
    pages = tuple(
        p.evolve(text="\n".join(line for _, line in z.slice_lines(p.text)))
        for p in doc.pages
    )
    return replace(doc, pages=pages)


def measure_accuracy(pairs: list[tuple[Path, str, list[str]]],
                     label: str) -> AccuracyReport:
    """``pairs`` is ``(pdf path, rel name, ground-truth Bates per page)``."""
    rep = AccuracyReport(label)
    t0 = time.perf_counter()

    # --- pass 1: propose from a bounded prefix ------------------------------
    head: list[DocumentRecord] = []
    for path, rel, _gt in pairs[:PROPOSAL_DOCS]:
        doc = _document_from_pdf(path, rel)
        if doc is not None:
            head.append(zone_only(doc))
    proposal = B.propose_format(head) if head else None
    decision = None
    if proposal is not None:
        rep.proposal = (f"{proposal.format.label} — proposed from "
                        f"{len(head)} document(s): {proposal.pages_matched} of "
                        f"{proposal.pages_scanned} page(s) matched, best "
                        f"document coverage {proposal.best_document_coverage_pct}%")
        decision = B.BatesDecision(status=B.DecisionStatus.CONFIRMED,
                                   format=proposal.format,
                                   decided_by="acceptance-run",
                                   decided_at="2026-08-01T00:00:00Z")
    else:
        rep.proposal = f"(none proposed from the first {len(head)} document(s))"
    del head

    # --- pass 2: extract ONCE, keeping only what Stage 3 reads --------------
    reduced: list[tuple[DocumentRecord, str, list[str]]] = []
    for path, rel, gt in pairs:
        doc = _document_from_pdf(path, rel)
        if doc is None:
            continue
        rep.documents += 1
        if len(doc.pages) != len(gt):
            rep.notes.append(
                f"{rel}: DocIQ read {len(doc.pages)} page(s), the ground truth "
                f"names {len(gt)} — compared positionally up to the shorter of "
                f"the two; the remainder counts as missed")
        reduced.append((zone_only(doc), rel, gt))
        del doc

    # --- the matter-wide census, which D-28's third gate is asked of --------
    census = B.matter_prefixes([d for d, _rel, _gt in reduced])
    rep.matter_prefixes = list(census)

    # --- pass 3: apply and score -------------------------------------------
    for doc, rel, gt in reduced:
        applied = B.apply_bates_reported((doc,), decision,
                                         matter_prefix_census=census)
        rep.normalization_available = applied.normalization_available
        rep.refused_reason = applied.refused_reason or ""
        for n in applied.normalized:
            rep.normalized.append((rel, n.page_no, n.read, n.applied, n.rule))
        stamped = applied.documents[0]
        n_pages = max(len(gt), len(stamped.pages))
        for i in range(n_pages):
            expected = gt[i] if i < len(gt) else None
            got = stamped.pages[i].bates if i < len(stamped.pages) else None
            page_no = i + 1
            if expected is None and got is None:
                continue
            rep.pages_compared += 1
            kind = (stamped.pages[i].kind.value if i < len(stamped.pages)
                    else "absent")
            slot = rep.by_kind.setdefault(kind, [0, 0])
            slot[0] += 1
            if expected is None:
                rep.false_positive.append((rel, page_no, got or ""))
            elif got is None:
                rep.missed.append((rel, page_no, expected))
            elif got.strip() == expected.strip():
                rep.correct += 1
                slot[1] += 1
            else:
                rep.wrong.append((rel, page_no, expected, got))
    rep.seconds = time.perf_counter() - t0
    return rep


# ---------------------------------------------------------------------------
# the negative control — absence must stay absent
# ---------------------------------------------------------------------------


def negative_control(root: Path, limit: int) -> AccuracyReport:
    """D-13's proof case: an unstamped corpus must propose NOTHING.

    A detector tuned until a stamped set scores 100% and never checked against
    an unstamped one has not been measured, it has been fitted.
    """
    rep = AccuracyReport("negative control — unstamped corpus")
    pdfs = sorted(root.rglob("*.pdf"))[:limit]
    t0 = time.perf_counter()

    # Same memory discipline as measure_accuracy, and here it is unavoidable:
    # this corpus is 2.6 GB of PDFs and holding every extracted document killed
    # the process before it reported. `propose_format` needs a corpus view, so
    # the DOCUMENTS are streamed and only their *candidates* are kept — the
    # tiny records detection actually reasons over.
    all_candidates: list[B.BatesCandidate] = []
    pages_by_key: dict[tuple, int] = {}
    for p in pdfs:
        d = _document_from_pdf(p, p.name)
        if d is None:
            continue
        rep.documents += 1
        rep.pages_compared += len(d.pages)
        from dociq.contracts import document_sort_key

        pages_by_key[document_sort_key(d)] = len(d.pages)
        all_candidates.extend(B.detect_candidates((d,)))
        del d

    # Re-apply propose_format's own thresholds to the streamed candidates. The
    # arithmetic is repeated rather than the function reused because the
    # function takes documents; the THRESHOLDS are read from the module so they
    # cannot drift apart from the shipped ones.
    from collections import Counter as _Counter

    by_shape: dict[tuple, list] = {}
    for c in all_candidates:
        by_shape.setdefault(c.format_key, []).append(c)
    proposed = None
    if by_shape:
        ranked = sorted(by_shape.items(),
                        key=lambda kv: (-len(kv[1]), -len(kv[0][0]), kv[0]))
        key, best = ranked[0]
        matched = _Counter(c.sort_key for c in best)
        best_pct = max((round(100 * n / pages_by_key[k])
                        for k, n in matched.items() if pages_by_key.get(k)),
                       default=0)
        if len(best) >= 2 and best_pct >= B.MIN_DOCUMENT_COVERAGE_PCT:
            proposed = (key, len(best), best_pct)

    if proposed is None:
        rep.proposal = (f"(none proposed — CORRECT; {len(all_candidates)} "
                        f"stamp-shaped line(s) seen, none clearing the "
                        f"{B.MIN_DOCUMENT_COVERAGE_PCT}% per-document bar)")
        rep.correct = rep.pages_compared
    else:
        key, n, pct = proposed
        rep.proposal = (f"PROPOSED prefix={key[0]!r} on an UNSTAMPED set — "
                        f"{n} page(s), best document coverage {pct}%")
        rep.false_positive.append((str(root), 0, str(key)))
    rep.seconds = time.perf_counter() - t0
    return rep


# ---------------------------------------------------------------------------


def _find_load_files(root: Path) -> list[Path]:
    return sorted(root.rglob("*.opt"), key=lambda p: str(p).lower()) or \
        sorted(root.rglob("*.OPT"), key=lambda p: str(p).lower())


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(prog="bates_acceptance")
    ap.add_argument("--corpus", help="the stamped production root")
    ap.add_argument("--negative-control", help="an unstamped corpus root")
    ap.add_argument("--negative-limit", type=int, default=60)
    ap.add_argument("--sample-docs", type=int, default=120,
                    help="how many load-file documents to run DocIQ over. "
                         "The continuity proof always covers the WHOLE set; "
                         "this bounds only the page-level comparison, and the "
                         "bound is reported with what it left out.")
    ap.add_argument("--max-mb", type=float, default=60.0,
                    help="skip individual PDFs larger than this in the sampled "
                         "comparison. Disclosed, never silent: the skipped "
                         "files are listed in the report.")
    ap.add_argument("--seed", type=int, default=20240529)
    ap.add_argument("--no-footer-reocr", action="store_true",
                    help="run with D-25's targeted footer re-OCR disabled, to "
                         "produce the before-number with the after-code")
    ap.add_argument("--only-ocr-docs", action="store_true",
                    help="restrict the page-level comparison to sampled "
                         "documents that contain at least one page DocIQ must "
                         "OCR. The footer re-OCR cannot change any other "
                         "document, so this measures exactly the pages that "
                         "can move — at a fraction of the machine time. The "
                         "documents dropped are counted in the report.")
    ap.add_argument("--out", default="", help="write the JSON report here")
    args = ap.parse_args(argv)

    global FOOTER_REOCR
    FOOTER_REOCR = not args.no_footer_reocr

    reports: dict = {"generated": time.strftime("%Y-%m-%dT%H:%M:%S"),
                     "method": "D-23: whole-set continuity + sampled page-level "
                               "comparison against the production's load files"}

    if args.negative_control:
        rep = negative_control(Path(args.negative_control), args.negative_limit)
        print(rep.render())
        reports["negative_control"] = rep.__dict__ | {"accuracy_pct": rep.accuracy_pct}

    if args.corpus:
        root = Path(args.corpus)
        print(f"\n=== corpus: {root}\n")

        # --- (a) continuity, whole set, from the load files -----------------
        for opt in _find_load_files(root):
            pages = parse_opt(opt)
            rep = continuity_from_opt(pages, f"load file {opt.name}")
            print(rep.render() + "\n")
            reports.setdefault("continuity", []).append(
                {"label": rep.label, "documents": rep.documents,
                 "pages": rep.pages, "checks": rep.checks,
                 "findings": rep.findings})

        # --- (a') continuity for the combined PDFs, from their names --------
        named: list[NamedRange] = []
        for p in sorted(root.rglob("*.pdf")):
            if "images" in [q.lower() for q in p.parts]:
                continue
            r = parse_filename_range(p)
            if r is not None:
                named.append(r)
        if named:
            counts: dict[Path, int] = {}
            for r in named:
                try:
                    from pypdf import PdfReader

                    counts[r.path] = len(PdfReader(str(r.path)).pages)
                except Exception as exc:
                    print(f"    ! page count for {r.path.name}: {exc}")
            rep = continuity_from_filenames(named, counts,
                                            "combined PDFs (filename ranges)")
            print(rep.render() + "\n")
            reports.setdefault("continuity", []).append(
                {"label": rep.label, "documents": rep.documents,
                 "pages": rep.pages, "checks": rep.checks,
                 "findings": rep.findings})

        # --- (b) page-level accuracy against the authoritative load file ----
        for opt in _find_load_files(root):
            pages = parse_opt(opt)
            base = opt.parent.parent  # <production>/data/<x>.opt -> <production>
            by_image: dict[str, list[str]] = defaultdict(list)
            for pg in pages:
                by_image[pg.image_rel].append(pg.bates)
            candidates = []
            skipped_big: list[str] = []
            for rel, gt in sorted(by_image.items()):
                path = base / rel
                if not path.is_file():
                    continue
                mb = path.stat().st_size / (1024 * 1024)
                if mb > args.max_mb:
                    skipped_big.append(f"{rel} ({mb:.0f} MB, {len(gt)} pages)")
                    continue
                candidates.append((path, rel, gt))
            rng = random.Random(args.seed)
            rng.shuffle(candidates)
            chosen = sorted(candidates[:args.sample_docs], key=lambda t: t[1])
            dropped_native = 0
            if args.only_ocr_docs:
                keep = []
                for path, rel, gt in chosen:
                    got = has_ocr_pages(path)
                    if got is False:
                        dropped_native += 1
                        continue
                    keep.append((path, rel, gt))   # None (unreadable) is kept
                chosen = keep
            rep = measure_accuracy(chosen, f"page-level vs {opt.name}")
            rep.notes.append(f"footer re-OCR (D-25): "
                             f"{'ON' if FOOTER_REOCR else 'OFF'}")
            if args.only_ocr_docs:
                rep.notes.append(
                    f"--only-ocr-docs: {dropped_native} sampled document(s) "
                    f"have no page DocIQ must OCR and were not re-measured; "
                    f"the footer re-OCR cannot reach them")
            rep.notes.append(
                f"sampled {len(chosen)} of {len(candidates)} eligible "
                f"document(s) (seed {args.seed}); "
                f"{len(skipped_big)} document(s) skipped for exceeding "
                f"--max-mb {args.max_mb}")
            for s in skipped_big[:20]:
                rep.notes.append(f"skipped: {s}")
            print(rep.render() + "\n")
            reports.setdefault("accuracy", []).append(
                rep.__dict__ | {"accuracy_pct": rep.accuracy_pct})

    if args.out:
        Path(args.out).write_text(json.dumps(reports, indent=2, default=str),
                                  encoding="utf-8")
        print(f"\nreport written to {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
